name: testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          pipenv run pytest tests -v
